# Generated by Django 5.2.11 on 2026-08-18 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0012_delete_contribution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserContribution',
        ),
    ]
